name: Deploy Backend to QA

on:
  push:
    branches:
      - stage

jobs:
  deploy:
    runs-on:
      - self-hosted
      - backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t sample-backend-api:latest .

      - name: Save Docker Image
        run: |
          docker save sample-backend-api:latest -o sample-backend-api.tar

      - name: Copy image to QA
        run: |
          scp -o StrictHostKeyChecking=no \
            sample-backend-api.tar \
            ubuntu@10.0.128.115:/opt/sample-backend/

      - name: Deploy on QA
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@10.0.128.115 << 'EOF'
            cd /opt/sample-backend
            docker load -i sample-backend-api.tar
            docker compose up -d --force-recreate
            docker image prune -f
          EOF
